import Header from "./Header"
import Cover from "./Cover"
import Application from "./Application"
import About from "./About"
import Catalog from "./Catalog"
import Offer from "./Offer"
import Contacts from "./Contacts"
import YandexMap from "./YandexMap"
import Partners from "./Partners"
import Footer from "./Footer"
import Form from "./Form"
import Modal from "./Modal"
import Menu from "./Menu"

export {Header, Cover, Application, About, Catalog, Offer, Contacts, YandexMap, Partners, Footer, Form, Modal, Menu}